ReplicaNumber: 1

argocd:
  syncwave:
    deployment: 5

containers:
  containerPort: 8080
  image: 'quay.io/shukshuk/harta-barta'
  tag: 'chart_v1'

service:
  servicePort: 8080

volume:
  mount:
    path: "/tmp/html"

probes:
  readiness:
    probeMapping:
      path: "/health/readiness"
      scheme: HTTP
    probeConfig:
      initialDelaySeconds: 1
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
  liveness:
    probeMapping:
      path: "/health/liveliness"
      scheme: HTTP
    probeConfig:
      initialDelaySeconds: 1
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3